#!/bin/bash
# generated by chatGPT
# In the above script, replace command with the actual command you want to execute with the line as an argument, and text_file.txt with the name of your text file.
# The & at the end of the command tells Bash to run the command in the background, which means that the script will continue executing without waiting for the command to finish before moving on to the next line in the text file.
# Note that if your command takes a long time to execute or produces a lot of output, running it in the background may cause issues with the script's output or performance. 
# If this is the case, you may want to consider running the command in the foreground instead.

while read line; do
    # execute command with $line as argument in the background
    command "$line" &
done < text_file.txt
